import type { Metadata } from 'next';
import { Chivo, Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistChivo = Chivo({
  variable: '--font-chivo',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full `}>
      <body
        className={`min-h-full flex flex-col antialiased ${geistChivo.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
