import { CategoriesProps, ProjectsProps, RegionsProps } from './types';

export const projects: ProjectsProps[] = [
  {
    id: 1,
    title: 'Galpão Industrial Comolatti',
    client: 'Grupo Comolatti',
    category: 'Industrial',
    location: 'Santos, SP',
    state: 'SP',
    region: 'Sudeste',
    area: '12.000 m²',
    year: '2024',
    duration: '8 meses',
    description:
      'Construção completa de galpão industrial com estrutura metálica, piso industrial de alta resistência, sistema de combate a incêndio e adequação às normas NR-12. O projeto incluiu áreas administrativas, vestiários, refeitório e docas para carga e descarga.',
    services: [
      'Estrutura Metálica',
      'Piso Industrial',
      'Instalações Elétricas',
      'Sistema de Incêndio',
      'Área Administrativa',
    ],
    images: [
      'https://images.unsplash.com/photo-1772299121503-cd62a57e3a26?w=1200',
      'https://images.unsplash.com/photo-1772209415876-76ea6cbc2f0c?w=1200',
      'https://images.pexels.com/photos/7108784/pexels-photo-7108784.jpeg?w=1200',
      'https://images.unsplash.com/photo-1768719951887-539ce3752a05?w=1200',
    ],
    featured: true,
  },
  {
    id: 2,
    title: 'Centro de Distribuição Iveco',
    client: 'Iveco Brasil',
    category: 'Industrial',
    location: 'Campinas, SP',
    state: 'SP',
    region: 'Sudeste',
    area: '25.000 m²',
    year: '2024',
    duration: '12 meses',
    description:
      'Centro de distribuição com infraestrutura completa para armazenamento e logística de peças automotivas. Projeto com pé-direito de 14 metros, sistema de sprinklers categoria Extra e pisos com capacidade para 8 toneladas/m².',
    services: [
      'Fundação Especial',
      'Estrutura Pré-moldada',
      'Cobertura Termoacústica',
      'Sistema de Docas',
      'Urbanização',
    ],
    images: [
      'https://images.unsplash.com/photo-1704297275778-8763889fa47d?w=1200',
      'https://images.unsplash.com/photo-1772299121503-cd62a57e3a26?w=1200',
      'https://images.pexels.com/photos/7108784/pexels-photo-7108784.jpeg?w=1200',
    ],
    featured: true,
  },
  {
    id: 3,
    title: 'Castor Colchões - Unidade Voluntários',
    client: 'Castor Colchões',
    category: 'Comercial',
    location: 'São Paulo, SP',
    state: 'SP',
    region: 'Sudeste',
    area: '800 m²',
    year: '2023',
    duration: '4 meses',
    description:
      'Reforma completa de loja de varejo com novo layout, sistema de climatização, iluminação em LED, fachada moderna e adequação à identidade visual da marca. Trabalho executado com a loja parcialmente em funcionamento.',
    services: [
      'Demolição Controlada',
      'Arquitetura de Interiores',
      'Climatização',
      'Iluminação LED',
      'Fachada',
    ],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200',
      'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=1200',
    ],
    featured: false,
  },
  {
    id: 4,
    title: 'Apartamento Bosque do Buriti',
    client: 'Construtora Bosque',
    category: 'Residencial',
    location: 'Goiânia, GO',
    state: 'GO',
    region: 'Centro-Oeste',
    area: '180 m²',
    year: '2024',
    duration: '3 meses',
    description:
      'Reforma completa de apartamento de alto padrão incluindo ampliação da sala, nova cozinha americana, troca de toda instalação elétrica e hidráulica, automação residencial e acabamentos premium.',
    services: [
      'Projeto de Interiores',
      'Instalações Completas',
      'Automação',
      'Acabamentos Premium',
      'Marcenaria',
    ],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200',
    ],
    featured: false,
  },
  {
    id: 5,
    title: 'Regularização AVCB - Express Grill',
    client: 'Express Grill Restaurantes',
    category: 'AVCB',
    location: 'Rio de Janeiro, RJ',
    state: 'RJ',
    region: 'Sudeste',
    area: '450 m²',
    year: '2024',
    duration: '2 meses',
    description:
      'Elaboração de projeto técnico e execução de todas as adequações necessárias para obtenção do Auto de Vistoria do Corpo de Bombeiros. Instalação de sistema de detecção de fumaça, extintores, iluminação de emergência e sinalização.',
    services: [
      'Projeto AVCB',
      'Sistema de Detecção',
      'Iluminação de Emergência',
      'Sinalização',
      'Acompanhamento de Vistoria',
    ],
    images: [
      'https://images.unsplash.com/photo-1768719951887-539ce3752a05?w=1200',
      'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1200',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200',
    ],
    featured: false,
  },
  {
    id: 6,
    title: 'Galpão Logístico Mercado Livre',
    client: 'Mercado Livre',
    category: 'Industrial',
    location: 'Cajamar, SP',
    state: 'SP',
    region: 'Sudeste',
    area: '45.000 m²',
    year: '2023',
    duration: '18 meses',
    description:
      'Mega centro de distribuição com tecnologia de ponta para e-commerce. Estrutura preparada para automação logística, sistemas de esteiras e robôs, área refrigerada para produtos sensíveis e certificação LEED.',
    services: [
      'Terraplenagem',
      'Estrutura Metálica',
      'Instalações Especiais',
      'Área Refrigerada',
      'Certificação LEED',
    ],
    images: [
      'https://images.unsplash.com/photo-1772209415876-76ea6cbc2f0c?w=1200',
      'https://images.unsplash.com/photo-1772299121503-cd62a57e3a26?w=1200',
      'https://images.pexels.com/photos/36467707/pexels-photo-36467707.jpeg?w=1200',
    ],
    featured: true,
  },
  {
    id: 7,
    title: 'Casa Rústica Vila Madalena',
    client: 'Particular',
    category: 'Residencial',
    location: 'São Paulo, SP',
    state: 'SP',
    region: 'Sudeste',
    area: '350 m²',
    year: '2024',
    duration: '6 meses',
    description:
      'Construção de residência em estilo rústico contemporâneo com estrutura em madeira de demolição, telhado aparente, piscina natural e paisagismo nativo. Integração total com área externa e sustentabilidade.',
    services: [
      'Construção Completa',
      'Estrutura em Madeira',
      'Piscina Natural',
      'Paisagismo',
      'Sistema de Reuso de Água',
    ],
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200',
    ],
    featured: false,
  },
  {
    id: 8,
    title: 'Showroom Terraço Itália',
    client: 'Terraço Itália Eventos',
    category: 'Comercial',
    location: 'São Paulo, SP',
    state: 'SP',
    region: 'Sudeste',
    area: '1.200 m²',
    year: '2023',
    duration: '5 meses',
    description:
      'Reforma do icônico espaço de eventos com preservação das características históricas e modernização de toda infraestrutura. Novo sistema de climatização, iluminação cênica e adequação de acessibilidade.',
    services: [
      'Restauração',
      'Climatização Central',
      'Iluminação Cênica',
      'Acessibilidade',
      'Acústica',
    ],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200',
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200',
      'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=1200',
    ],
    featured: true,
  },
];

export const categories: CategoriesProps[] = [
  { id: 'all', label: 'Todos' },
  { id: 'Industrial', label: 'Industrial' },
  { id: 'Comercial', label: 'Comercial' },
  { id: 'Residencial', label: 'Residencial' },
  { id: 'AVCB', label: 'AVCB' },
];

export const regions: RegionsProps[] = [
  { id: 'all', label: 'Todas as Regiões' },
  { id: 'Sudeste', label: 'Sudeste' },
  { id: 'Sul', label: 'Sul' },
  { id: 'Centro-Oeste', label: 'Centro-Oeste' },
  { id: 'Nordeste', label: 'Nordeste' },
  { id: 'Norte', label: 'Norte' },
];
